CREATE SCHEMA IF NOT EXISTS VEHMST;
SET SCHEMA VEHMST;

create table tele_carline_mst
(
    create_date  date,
    update_date  date,
    carline_id   bigint generated by default as identity,
    create_user  varchar(100),
    update_user  varchar(100),
    carline      varchar(250) not null,
    carline_desc varchar(250),
    primary key (carline_id)
);
create table tele_dcm_gen_mst
(
    create_date date,
    update_date date,
    dcm_gen_id  bigint generated by default as identity,
    market_id   bigint      not null,
    dcm_gen     varchar(15) not null,
    tsp_code    varchar(15),
    create_user varchar(100),
    update_user varchar(100),
    primary key (dcm_gen_id)
);
create table tele_dcm_mst
(
    create_date     date,
    update_date     date,
    dcm_id          bigint generated by default as identity,
    dcm_software_id bigint,
    pairing_date    timestamp(6),
    scrap_date      timestamp(6),
    shipping_date   timestamp(6),
    dcm_number      varchar(10),
    mfr_code        varchar(15),
    msisdn          varchar(15),
    imei            varchar(16),
    iccid           varchar(20),
    create_user     varchar(100),
    update_user     varchar(100),
    primary key (dcm_id)
);
create table tele_dcm_software_mst
(
    create_date                date,
    release_date               date,
    update_date                date,
    dcm_gen_id                 bigint      not null,
    dcm_software_id            bigint generated by default as identity,
    conti_r_nbr                varchar(25),
    dcm_software_short_version varchar(25),
    dcm_software_version       varchar(25) not null,
    release_note               varchar(50),
    create_user                varchar(100),
    update_user                varchar(100),
    official_loads_info        varchar(4000),
    primary key (dcm_software_id)
);
create table tele_features_mst
(
    create_date            date         not null,
    delivery_checklist_flg varchar(1),
    monroney_label_flg     varchar(1),
    remote_flg             varchar(1)   not null,
    update_date            date,
    feature_id             bigint generated by default as identity,
    create_user            varchar(100) not null,
    update_user            varchar(100),
    feature_code           varchar(250) not null,
    feature_desc           varchar(250) not null,
    primary key (feature_id)
);
create table tele_global_model_mst
(
    create_date           date,
    update_date           date,
    global_model_id       bigint generated by default as identity,
    global_exterior_color varchar(15) not null,
    global_interior_color varchar(15) not null,
    global_model_code     varchar(15) not null,
    global_option_code    varchar(15),
    global_spec_code      varchar(15) not null,
    create_user           varchar(100),
    update_user           varchar(100),
    primary key (global_model_id)
);
create table tele_head_unit_gen_mst
(
    create_date      date,
    update_date      date,
    head_unit_gen_id bigint generated by default as identity,
    market_id        bigint      not null,
    head_unit_gen    varchar(15) not null,
    create_user      varchar(100),
    update_user      varchar(100),
    hu_provider_code varchar(250),
    primary key (head_unit_gen_id)
);
create table tele_local_color_mst
(
    create_date          date,
    update_date          date,
    local_color_id       bigint       not null,
    market_id            bigint       not null,
    exterior_color_code  varchar(15)  not null,
    interior_color_code  varchar(15)  not null,
    create_user          varchar(100),
    local_color_key      varchar(100) not null,
    update_user          varchar(100),
    base_color           varchar(250) not null,
    local_ext_color_desc varchar(250),
    local_int_color_desc varchar(250),
    primary key (local_color_id)
);
create table tele_local_model_mst
(
    create_date      date,
    model_year_desc  varchar(4),
    update_date      date,
    model_year       varchar(6)   not null,
    carline_id       bigint       not null,
    dcm_gen_id       bigint,
    head_unit_gen_id bigint,
    local_model_id   bigint generated by default as identity,
    market_id        bigint       not null,
    model_code       varchar(15)  not null,
    motive_power     varchar(15)  not null,
    option_code      varchar(15),
    create_user      varchar(100),
    local_model_key  varchar(100) not null,
    update_user      varchar(100),
    body_style       varchar(250),
    drive_train      varchar(250),
    engine_size      varchar(250),
    model_desc       varchar(250),
    model_trim_desc  varchar(250),
    transmission     varchar(250),
    trim             varchar(250),
    turbo            varchar(250),
    primary key (local_model_id)
);
create table tele_local_model_spec_mst
(
    create_date                 date,
    update_date                 date,
    local_spec_id               bigint generated by default as identity,
    market_id                   bigint not null,
    spec_code                   varchar(15),
    create_user                 varchar(100),
    update_user                 varchar(100),
    spec_certification_verbiage varchar(250),
    primary key (local_spec_id)
);
create table tele_market
(
    create_date  date,
    update_date  date,
    market_id    bigint generated by default as identity,
    org_id       bigint       not null,
    create_user  varchar(100),
    update_user  varchar(100),
    country_code varchar(255) not null,
    primary key (market_id)
);
create table tele_model_features
(
    create_date          date,
    effective_end_date   date,
    effective_start_date date   not null,
    update_date          date,
    FEATURE_ID           bigint not null,
    MODEL_ID             bigint not null,
    create_user          varchar(100),
    update_user          varchar(100),
    primary key (FEATURE_ID, MODEL_ID)
);
create table tele_org
(
    create_date date,
    update_date date,
    org_id      bigint not null,
    create_user varchar(100),
    org_name    varchar(100),
    update_user varchar(100),
    primary key (org_id)
);
create table tele_vin_master
(
    create_date      date,
    production_date  date,
    telematics_flag  varchar(1)  not null,
    update_date      date,
    global_model_id  bigint,
    local_color_id   bigint,
    local_model_id   bigint,
    local_spec_id    bigint,
    market_id        bigint      not null,
    isp_id           varchar(10),
    case_number      varchar(15),
    immobilizer_key  varchar(15),
    key_number       varchar(15),
    vehicle_source   varchar(15),
    vin              varchar(17) not null,
    engine_number    varchar(20),
    create_user      varchar(100),
    distributor_code varchar(100),
    update_user      varchar(100),
    vehicle_id       varchar(255),
    primary key (vin)
);
create table tele_vin_status
(
    create_date               date,
    subscription_flag         boolean,
    traffic_subscription_flag boolean,
    update_date               date,
    comm_check_date           timestamp(6),
    dcm_id                    bigint,
    factory_feed_date         timestamp(6),
    fota_process_date         timestamp(6),
    fota_vehicle_id           bigint,
    provisioning_date         timestamp(6),
    msisdn                    varchar(15),
    vin                       varchar(17) not null,
    create_user               varchar(100),
    fota_process_name         varchar(100),
    fota_status               varchar(100),
    mno_state                 varchar(100),
    provisioning_status       varchar(100),
    subscription_category     varchar(100),
    update_user               varchar(100),
    mode_file_name            varchar(200),
    primary key (vin)
);
CREATE TABLE TELE_COUNTRY
(
  COUNTRY_CODE CHAR(3),
  COUNTRY_NAME VARCHAR2(100),
  CREATE_USER VARCHAR2(100),
  CREATE_DATE DATE,
  UPDATE_USER VARCHAR2(100),
  UPDATE_DATE DATE,
  CONSTRAINT SYS_C0019941 CHECK ("COUNTRY_CODE" IS NOT NULL),
  CONSTRAINT TELE_COUNTRY_PK PRIMARY KEY (COUNTRY_CODE)
);
CREATE UNIQUE INDEX TELE_COUNTRY_PK ON TELE_COUNTRY (COUNTRY_CODE);
alter table if exists tele_dcm_gen_mst add constraint FK8va6j7j07c585sq1jmkajx25t foreign key (market_id) references tele_market;
alter table if exists tele_dcm_mst add constraint FKo8c739o5de7tmaaopn9lj17xx foreign key (dcm_software_id) references tele_dcm_software_mst on delete restrict;
alter table if exists tele_dcm_software_mst add constraint FKtkbii8ybirlc810at9x7827dh foreign key (dcm_gen_id) references tele_dcm_gen_mst on delete restrict;
alter table if exists tele_local_color_mst add constraint FKgf4gognbrar3786c9quws3x0q foreign key (market_id) references tele_market on delete restrict;
alter table if exists tele_local_model_mst add constraint FKg87rs2s9n83hu35x9rhp66305 foreign key (carline_id) references tele_carline_mst on delete restrict;
alter table if exists tele_local_model_mst add constraint FKj213b9ystx3w29kjrs6e8d405 foreign key (dcm_gen_id) references tele_dcm_gen_mst on delete restrict;
alter table if exists tele_local_model_mst add constraint FKt9yu24enhkvsovnvyjwxbsx9i foreign key (head_unit_gen_id) references tele_head_unit_gen_mst on delete restrict;
alter table if exists tele_local_model_mst add constraint FK1gdyqnn4bbkw5w31e5m0g60ob foreign key (market_id) references tele_market;
alter table if exists tele_local_model_spec_mst add constraint FKaiyepv1hgrasd4a664i3b7u92 foreign key (market_id) references tele_market on delete restrict;
alter table if exists tele_market add constraint FKpnck2lu7woto1gxvecnxejwux foreign key (org_id) references tele_org on delete restrict;
alter table if exists tele_model_features add constraint FKnl48pcc6trcuq8e6ggrtagrn3 foreign key (feature_id) references tele_features_mst on delete restrict;
alter table if exists tele_model_features add constraint FK7kvp8i65o1ahmc1hrhlklu8rr foreign key (model_id) references tele_local_model_mst on delete restrict;
alter table if exists tele_vin_master add constraint FKm98pb5ylxoy830wcsaqhvfy19 foreign key (global_model_id) references tele_global_model_mst on delete restrict;
alter table if exists tele_vin_master add constraint FKexft0tm6des7yoku1jed9w0tm foreign key (local_color_id) references tele_local_color_mst on delete restrict;
alter table if exists tele_vin_master add constraint FK1flndr6gcyoe2cb2w8cnowg1e foreign key (local_model_id) references tele_local_model_mst;
alter table if exists tele_vin_master add constraint FKm701jdqnoknwwlnk6y7huwl38 foreign key (local_spec_id) references tele_local_model_spec_mst on delete restrict;
alter table if exists tele_vin_master add constraint FKik2hero2gbkb7ddyy3tk0431t foreign key (market_id) references tele_market on delete restrict;
alter table if exists tele_vin_status add constraint FKo7igkusc2kv0q66y3j0k4r1j3 foreign key (dcm_id) references tele_dcm_mst on delete restrict;
alter table if exists tele_vin_status add constraint FKkbht4yr773a7uaotd130c1gkn foreign key (vin) references tele_vin_master on delete restrict;
